# Generated by Django 4.2.30 on 2026-09-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credential_udc_img',
            field=models.FileField(blank=True, db_column='credential_udc_img', null=True, upload_to='credentials/'),
        ),
    ]
