# Generated by Django 4.2.30 on 2026-08-18 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id_address_i', models.AutoField(db_column='id_address_i', primary_key=True, serialize=False)),
                ('name_address_v', models.CharField(db_column='name_address_v', max_length=100)),
                ('hour_init_t', models.TimeField(blank=True, db_column='hour_init_t', null=True)),
                ('latitude_d', models.DecimalField(db_column='latitude_d', decimal_places=12, max_digits=18)),
                ('longitude_d', models.DecimalField(db_column='longitude_d', decimal_places=12, max_digits=18)),
                ('date_create_t', models.DateTimeField(auto_now_add=True, db_column='date_create_t')),
                ('date_update_t', models.DateTimeField(auto_now=True, db_column='date_update_t')),
                ('is_active_b', models.BooleanField(db_column='is_active_b', default=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id_car_i', models.AutoField(db_column='id_car_i', primary_key=True, serialize=False)),
                ('type_car_v', models.CharField(db_column='type_car_v', max_length=50)),
                ('mark_car_v', models.CharField(db_column='mark_car_v', max_length=50)),
                ('model_car_v', models.CharField(db_column='model_car_v', max_length=50)),
                ('year_car_i', models.IntegerField(db_column='year_car_i')),
                ('color_car_v', models.CharField(db_column='color_car_v', max_length=50)),
                ('seating_car_i', models.IntegerField(db_column='seating_car_i')),
                ('plates_car_v', models.CharField(db_column='plates_car_v', max_length=50)),
                ('lic_user_car_v', models.CharField(db_column='lic_user_car_v', max_length=50)),
                ('date_create_t', models.DateTimeField(auto_now_add=True, db_column='date_create_t')),
                ('date_update_t', models.DateTimeField(auto_now=True, db_column='date_update_t')),
                ('is_active_b', models.BooleanField(db_column='is_active_b', default=True)),
            ],
            options={
                'db_table': 'car',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id_journey_i', models.AutoField(db_column='id_journey_i', primary_key=True, serialize=False)),
                ('cost_journey_d', models.DecimalField(db_column='cost_journey_d', decimal_places=2, max_digits=10)),
                ('available_seats_i', models.IntegerField(db_column='available_seats_i')),
                ('status_v', models.CharField(db_column='status_v', max_length=20)),
                ('date_create_t', models.DateTimeField(auto_now_add=True, db_column='date_create_t')),
                ('date_update_t', models.DateTimeField(auto_now=True, db_column='date_update_t')),
                ('is_active_b', models.BooleanField(db_column='is_active_b', default=True)),
            ],
            options={
                'db_table': 'journey',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id_rating_i', models.AutoField(db_column='id_rating_i', primary_key=True, serialize=False)),
                ('rating_f', models.FloatField(db_column='rating_f')),
                ('comment_user_v', models.CharField(db_column='comment_user_v', max_length=225)),
                ('date_create_t', models.DateTimeField(auto_now_add=True, db_column='date_create_t')),
                ('date_update_t', models.DateTimeField(auto_now=True, db_column='date_update_t')),
                ('is_active_b', models.BooleanField(db_column='is_active_b', default=True)),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id_route_i', models.AutoField(db_column='id_route_i', primary_key=True, serialize=False)),
                ('map_polyline_v', models.TextField(blank=True, db_column='map_polyline_v', null=True)),
                ('time_route_t', models.TimeField(blank=True, db_column='time_route_t', null=True)),
                ('date_create_t', models.DateTimeField(auto_now_add=True, db_column='date_create_t')),
                ('date_update_t', models.DateTimeField(auto_now=True, db_column='date_update_t')),
                ('is_active_b', models.BooleanField(db_column='is_active_b', default=True)),
                ('id_address_destiny_i', models.ForeignKey(db_column='id_address_destiny_i', on_delete=django.db.models.deletion.CASCADE, related_name='routes_destination', to='rides.address')),
                ('id_address_origin_i', models.ForeignKey(db_column='id_address_origin_i', on_delete=django.db.models.deletion.CASCADE, related_name='routes_origin', to='rides.address')),
            ],
            options={
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation_i', models.AutoField(db_column='id_reservation_i', primary_key=True, serialize=False)),
                ('price_user_pass_d', models.DecimalField(db_column='price_user_pass_d', decimal_places=2, max_digits=10)),
                ('date_create_t', models.DateTimeField(auto_now_add=True, db_column='date_create_t')),
                ('date_update_t', models.DateTimeField(auto_now=True, db_column='date_update_t')),
                ('is_active_b', models.BooleanField(db_column='is_active_b', default=True)),
                ('id_journey_reservation_i', models.ForeignKey(db_column='id_journey_reservation_i', on_delete=django.db.models.deletion.CASCADE, to='rides.journey')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
