# Generated by Django 4.2.30 on 2026-08-18 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id_user_passenger_reservation_i',
            field=models.ForeignKey(db_column='id_user_passenger_reservation_i', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='id_journey_rating_i',
            field=models.ForeignKey(db_column='id_journey_rating_i', on_delete=django.db.models.deletion.CASCADE, to='rides.journey'),
        ),
        migrations.AddField(
            model_name='rating',
            name='id_user_rating_i',
            field=models.ForeignKey(db_column='id_user_rating_i', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journey',
            name='id_address_journey_i',
            field=models.ForeignKey(blank=True, db_column='id_address_journey_i', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rides.address'),
        ),
        migrations.AddField(
            model_name='journey',
            name='id_route_journey_i',
            field=models.ForeignKey(db_column='id_route_journey_i', on_delete=django.db.models.deletion.CASCADE, to='rides.route'),
        ),
        migrations.AddField(
            model_name='journey',
            name='id_user_car_journey_i',
            field=models.ForeignKey(db_column='id_user_car_journey_i', on_delete=django.db.models.deletion.CASCADE, to='rides.car'),
        ),
        migrations.AddField(
            model_name='car',
            name='id_user_car_i',
            field=models.ForeignKey(db_column='id_user_car_i', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
