# Generated by Django 4.2.30 on 2026-09-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='lic_user_car_v',
            field=models.FileField(blank=True, db_column='lic_user_car_v', max_length=255, null=True, upload_to='licenses/'),
        ),
    ]
