# Generated by Django 5.0.4 on 2026-09-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_update_real_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seat_number_i',
            field=models.IntegerField(blank=True, db_column='seat_number_i', null=True),
        ),
    ]
