# Generated by Django 5.0.4 on 2026-09-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_reservation_seat_number_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='passenger_lat_d',
            field=models.DecimalField(blank=True, db_column='passenger_lat_d', decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='passenger_lng_d',
            field=models.DecimalField(blank=True, db_column='passenger_lng_d', decimal_places=8, max_digits=11, null=True),
        ),
    ]
