# Generated by Django 5.0.4 on 2026-09-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_reservation_passenger_lat_d_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='passenger_lat_d',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='passenger_lng_d',
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_lat',
            field=models.DecimalField(blank=True, db_column='pickup_lat_d', decimal_places=12, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_lng',
            field=models.DecimalField(blank=True, db_column='pickup_lng_d', decimal_places=12, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_name_v',
            field=models.CharField(blank=True, db_column='pickup_name_v', max_length=150, null=True),
        ),
    ]
